@startuml
    package ActorManagement {
        User --> (getActors)
        User --> (getActorByNameAndSurname)
        User --> (getActorsByAge)
        User --> (getActorsByCountry)
        User --> (getActorsByGender)
    }
@enduml