@startuml
    package DirectorManagement {
        User --> (getDirectors)
        User --> (getDirectorByNameAndSurname)
        User --> (getDirectorsByAge)
        User --> (getDirectorsByCountry)
        User --> (getDirectorsByGender)
    }
@enduml